name: publish

on:
  push:
    branches:
      - main

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build
        run: make build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out
